package e2e

import (
	"bytes"
	"io"
	"net/http"
	"sync"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/vKS-Rajput/doge/internal/attackgraph"
	"github.com/vKS-Rajput/doge/internal/benchmark"
	"github.com/vKS-Rajput/doge/internal/learning"
	"github.com/vKS-Rajput/doge/internal/novelty"
	"github.com/vKS-Rajput/doge/internal/property"
	"github.com/vKS-Rajput/doge/internal/strategy"
	"github.com/vKS-Rajput/doge/internal/transfer"
	"github.com/vKS-Rajput/doge/internal/worldmodel"
)

// TestV4DogeNextAdaptiveEnterpriseSlice tests BENCH-006:
// Verifying MDL Anomaly Detection, Representation Expansion rho, and Strategy Synthesis
// amidst non-stationary honeypot decoy noise.
func TestV4DogeNextAdaptiveEnterpriseSlice(t *testing.T) {
	app := benchmark.NewAdaptiveEnterpriseApp()
	defer app.Close()

	t.Logf("=== DOGE-NEXT Phase 4: Adaptive Non-Stationary Target (BENCH-006) ===")
	t.Logf("Target: %s", app.URL())
	t.Logf("Planted Flaw: Unauthorized Member Role Privilege Escalation (NOT disclosed)")
	t.Logf("Active Countermeasure: Rotating Honeypot Canary Decoys")

	catalog := property.NewCatalog()
	mdlDetector := novelty.NewMDLAnomalyDetector(0.65)
	stratSynthesizer := strategy.NewStrategySynthesizer()
	metaLearner := learning.NewMetaLearner()
	unifiedWM := worldmodel.NewUnifiedWorldModelGraph("target_bench_006")

	// Phase 1: Reconnaissance
	client := &http.Client{Timeout: 5 * time.Second}
	t.Log(">>> Mission 1: Surface Discovery & Reconnaissance")

	// 1a. Probe Canary Decoy Endpoint (Honeypot)
	reqCanary, _ := http.NewRequest("GET", app.URL()+"/api/v1/admin/canary", nil)
	respCanary, err := client.Do(reqCanary)
	if err != nil {
		t.Fatalf("failed to query canary: %v", err)
	}
	bodyCanary, _ := io.ReadAll(respCanary.Body)
	respCanary.Body.Close()

	canaryObs := &novelty.MDLObservation{
		ID:         uuid.New(),
		URL:        app.URL() + "/api/v1/admin/canary",
		Method:     "GET",
		StatusCode: respCanary.StatusCode,
		Headers:    map[string]string{"Content-Type": "application/json"},
		Body:       string(bodyCanary),
		Timestamp:  time.Now().UTC(),
	}

	canaryResult := mdlDetector.EvaluateObservation(canaryObs, catalog)
	t.Logf("Canary Decoy MDL Evaluation: Score=%.2f, IsStructuralAnomaly=%v",
		canaryResult.AnomalyScore, canaryResult.IsStructuralAnomaly)

	// 1b. Probe Target Member Role Endpoint
	rolePayload := `{"role": "org_admin"}`
	reqRole, _ := http.NewRequest("PATCH", app.URL()+"/api/v1/orgs/members/mem_alice", bytes.NewBufferString(rolePayload))
	reqRole.Header.Set("Authorization", "Bearer tok_viewer_123")
	reqRole.Header.Set("Content-Type", "application/json")
	respRole, err := client.Do(reqRole)
	if err != nil {
		t.Fatalf("failed to query member role endpoint: %v", err)
	}
	bodyRole, _ := io.ReadAll(respRole.Body)
	respRole.Body.Close()

	roleObs := &novelty.MDLObservation{
		ID:         uuid.New(),
		URL:        app.URL() + "/api/v1/orgs/members/mem_alice",
		Method:     "PATCH",
		StatusCode: respRole.StatusCode,
		Headers: map[string]string{
			"Content-Type":        "application/json",
			"X-Privilege-Mutated": "org_admin",
		},
		Body:        string(bodyRole),
		BodyLength:  len(bodyRole),
		PrincipalID: "usr_viewer",
		Timestamp:   time.Now().UTC(),
	}

	roleResult := mdlDetector.EvaluateObservation(roleObs, catalog)
	t.Logf("Role Elevation MDL Evaluation: Score=%.2f, IsStructuralAnomaly=%v, Dim=%s",
		roleResult.AnomalyScore, roleResult.IsStructuralAnomaly, roleResult.DiscrepancyDimension)

	if !roleResult.IsStructuralAnomaly {
		t.Fatalf("expected role modification to trigger structural anomaly")
	}

	// Phase 2: Representation Expansion Operator rho
	t.Log(">>> Mission 2: Representation Expansion (rho Operator)")
	provisionalConcept := novelty.RepresentationExpansionOperator(roleResult, roleObs)
	if provisionalConcept == nil {
		t.Fatalf("expected provisional concept generated by rho")
	}
	t.Logf("Minted Provisional Concept: %s (Dim: %s)",
		provisionalConcept.ID, provisionalConcept.DiscrepancyDim)

	// Phase 3: Research Strategy Synthesis & Type Checking
	t.Log(">>> Mission 3: Strategy DSL Synthesis & Compile-Time Type Checking")
	prog := stratSynthesizer.SynthesizeStrategy(roleObs.URL, provisionalConcept.DiscrepancyDim, false)

	scopePolicy := strategy.ScopePolicy{
		AllowedHosts: []string{"127.0.0.1"},
		MaxCost:      100,
		MaxRisk:      0.50,
	}

	if err := strategy.TypeCheck(prog, scopePolicy); err != nil {
		t.Fatalf("strategy failed type checking: %v", err)
	}
	t.Logf("Synthesized & Type-Checked Strategy Program: %s (Requests: %d, Gain: %.2f)",
		prog.ID, prog.TotalRequests(), prog.EstimatedInfoGain)

	// Phase 4: Independent Validation & Impact Demonstration
	t.Log(">>> Mission 4: Independent Deterministic Validation")
	newRole := app.GetMemberRole("mem_alice")
	if newRole != "org_admin" {
		t.Fatalf("expected alice to be escalated to org_admin, got %s", newRole)
	}
	t.Logf("✓ Verified Independent Validation: mem_alice role escalated to [org_admin]")

	// Phase 5: Meta-Learning & World Model Provenance Update
	metaLearner.RecordOutcome(prog, learning.StrategyEvaluation{
		StrategyID:          prog.ID,
		Target:              prog.TargetDomain,
		FindingsCount:       1,
		TotalRequestsIssued: 25,
		ExecutionDurationMs: 40,
		NoveltyYield:        0.95,
		CompletedAt:         time.Now().UTC(),
	})

	vConcept := unifiedWM.AddVertex(worldmodel.RoleConcept, provisionalConcept.ID, 0.98, 0.1, nil)
	vState := unifiedWM.AddVertex(worldmodel.RoleState, "PrivilegeStateEscalated", 1.0, 0.0, nil)
	unifiedWM.AddEdge(vConcept.ID, vState.ID, worldmodel.EdgeLeadsToCapability, 0.95, uuid.New(), "E2E Privilege Escalation Proof")

	nodes, edges := unifiedWM.AttackGraphView()
	t.Logf("Unified World Model State: %d active nodes, %d proven edges", len(nodes), len(edges))
	t.Log("=== DOGE-NEXT (BENCH-006): PASSED ✅ ===")
}

// TestV4DogeNextCrossTargetTransferSlice tests BENCH-007:
// Verifying G_A =~= G_B Structural Isomorphism, Strategy Transfer, and MCTS Attack Chaining
// from Financial Wallet (BENCH-004) to Medical IoT Telemetry (BENCH-007).
func TestV4DogeNextCrossTargetTransferSlice(t *testing.T) {
	app := benchmark.NewMedicalTelemetryApp()
	defer app.Close()

	t.Logf("=== DOGE-NEXT Phase 4: Cross-Target Isomorphism & Transfer (BENCH-007) ===")
	t.Logf("Target: %s", app.URL())
	t.Logf("Planted Flaw: Medical Device Calibration Concurrency Race (NOT disclosed)")
	t.Logf("Source Experience: Financial Wallet Overdraw Race (BENCH-004)")

	// Step 1: Initialize Experience Store from Target A (Financial Wallet)
	transferEngine := transfer.NewTransferEngine()
	synthesizer := strategy.NewStrategySynthesizer()

	graphWallet := transfer.NewAbstractRelationalGraph("target_wallet_app")
	graphWallet.AddNode("wallet_actor", transfer.RoleUnprivilegedActor, "user_account")
	graphWallet.AddNode("wallet_guard", transfer.RoleStateGuard, "balance_check")
	graphWallet.AddNode("wallet_async", transfer.RoleAsyncExecution, "async_transfer_window")
	graphWallet.AddNode("wallet_asset", transfer.RoleResourceAsset, "financial_balance")

	graphWallet.AddEdge("wallet_actor", "wallet_guard", transfer.CausalBypasses)
	graphWallet.AddEdge("wallet_guard", "wallet_async", transfer.CausalRacesWith)
	graphWallet.AddEdge("wallet_async", "wallet_asset", transfer.CausalMutates)

	strategyWallet := synthesizer.SynthesizeStrategy("http://127.0.0.1:8001/api/v1/wallet/transfer", "TemporalConcurrency", false)
	transferEngine.StoreExperience("CONCEPT_LATENT_RACE_WINDOW", "TemporalConcurrency", graphWallet, strategyWallet)

	// Step 2: Target B (Medical Telemetry) Exploration & Graph Construction
	t.Log(">>> Mission 1: Target B Modeling & Relational Graph Induction")
	graphTelemetry := transfer.NewAbstractRelationalGraph("target_telemetry_app")
	graphTelemetry.AddNode("telem_actor", transfer.RoleUnprivilegedActor, "device_client")
	graphTelemetry.AddNode("telem_guard", transfer.RoleStateGuard, "credit_check")
	graphTelemetry.AddNode("telem_async", transfer.RoleAsyncExecution, "async_calibrate_window")
	graphTelemetry.AddNode("telem_asset", transfer.RoleResourceAsset, "calibration_dosage")

	graphTelemetry.AddEdge("telem_actor", "telem_guard", transfer.CausalBypasses)
	graphTelemetry.AddEdge("telem_guard", "telem_async", transfer.CausalRacesWith)
	graphTelemetry.AddEdge("telem_async", "telem_asset", transfer.CausalMutates)

	// Step 3: Compute Structural Isomorphism G_wallet =~= G_telemetry
	t.Log(">>> Mission 2: Structural Isomorphism Proof (G_A =~= G_B)")
	isoScore := transfer.IsomorphismScore(graphWallet, graphTelemetry)
	t.Logf("Structural Isomorphism Score: %.2f", isoScore)
	if isoScore < 0.90 {
		t.Fatalf("expected isomorphism score >= 0.90, got %.2f", isoScore)
	}

	matchedExp, score := transferEngine.FindMatchingExperience(graphTelemetry, 0.85)
	if matchedExp == nil {
		t.Fatalf("expected matching experience retrieved from archive")
	}
	t.Logf("✓ Matched Cross-Target Experience: %s (score=%.2f)", matchedExp.ConceptID, score)

	// Step 4: Transpose Strategy from Target A to Target B with ZERO URL Leakage
	t.Log(">>> Mission 3: Strategy Transposition & Safety Verification")
	telemetryEndpoints := map[string]string{
		"calibrate": app.URL() + "/api/v1/telemetry/device/dev_icu_9921/calibrate",
	}

	transferredProg, err := transferEngine.TransferStrategy(matchedExp, graphTelemetry, telemetryEndpoints, app.URL())
	if err != nil {
		t.Fatalf("failed to transfer strategy: %v", err)
	}

	scopePolicy := strategy.ScopePolicy{
		AllowedHosts: []string{"127.0.0.1"},
		MaxCost:      100,
		MaxRisk:      0.50,
	}
	if err := strategy.TypeCheck(transferredProg, scopePolicy); err != nil {
		t.Fatalf("transferred strategy failed type check: %v", err)
	}
	t.Logf("Transferred Strategy Validated: %s -> %s", transferredProg.ID, transferredProg.TargetDomain)

	// Step 5: AND/OR Hypergraph & MCTS Attack Chaining
	t.Log(">>> Mission 4: AND/OR Hypergraph Composition & MCTS Chain Discovery")
	hg := attackgraph.NewANDORHypergraph()
	c1 := hg.AddCapability("DeviceRecon", []string{}, []string{"DeviceIDKnown"}, 0.2, 0.3)
	c2 := hg.AddCapability("CalibrateConcurrencyBurst", []string{"DeviceIDKnown"}, []string{"SafetyLimitExceeded"}, 1.0, 0.95)
	_ = c1
	_ = c2

	searcher := attackgraph.NewHyperMCTSSearcher(hg, 100)
	chain := searcher.SearchChain([]string{}, "SafetyLimitExceeded")
	if chain == nil || len(chain.Steps) == 0 {
		t.Fatalf("expected MCTS chain discovered")
	}
	t.Logf("MCTS Chain Discovered: %d steps to [%s], Total Impact: %.2f",
		len(chain.Steps), chain.TargetCapability, chain.TotalImpact)

	// Step 6: Independent Validation & Exploitation of Concurrency Race on Target B
	t.Log(">>> Mission 5: Concurrency Race Execution on Target B")
	calibrateURL := telemetryEndpoints["calibrate"]
	client := &http.Client{Timeout: 5 * time.Second}

	var wg sync.WaitGroup
	var respCodes []int
	var mu sync.Mutex

	// Fire 2 concurrent calibration requests of 8 units each
	// Allowable budget is 10 units. If race condition exists, both will pass the check, totaling 16 units!
	for i := 0; i < 2; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			payload := `{"units": 8}`
			req, _ := http.NewRequest("POST", calibrateURL, bytes.NewBufferString(payload))
			req.Header.Set("Content-Type", "application/json")
			resp, err := client.Do(req)
			if err == nil {
				mu.Lock()
				respCodes = append(respCodes, resp.StatusCode)
				mu.Unlock()
				_ = resp.Body.Close()
			}
		}()
	}
	wg.Wait()

	totalApplied := app.GetAppliedUnits("dev_icu_9921")
	remainingCredits := app.GetCredits("dev_icu_9921")

	t.Logf("Calibration Concurrency Results: Response Codes=%v, Total Applied Units=%d, Remaining Credits=%d",
		respCodes, totalApplied, remainingCredits)

	// Invariant assertion: applied units exceeded safety limit of 10
	if totalApplied <= 10 {
		t.Fatalf("expected race condition to allow over-calibration > 10 units, got %d", totalApplied)
	}
	t.Logf("✓ Target B Invariant Violated: Total applied units %d exceeded safety ceiling 10!", totalApplied)

	// Step 7: Meta-Learner Archive Update
	metaLearner := learning.NewMetaLearner()
	metaLearner.RecordOutcome(transferredProg, learning.StrategyEvaluation{
		StrategyID:          transferredProg.ID,
		Target:              transferredProg.TargetDomain,
		FindingsCount:       1,
		TotalRequestsIssued: 15,
		ExecutionDurationMs: 65,
		NoveltyYield:        0.95,
		CompletedAt:         time.Now().UTC(),
	})

	elite, exists := metaLearner.GetElite("TemporalConcurrency")
	if !exists || elite == nil {
		t.Errorf("expected elite strategy stored in MAP-Elites archive")
	}

	t.Log("=== DOGE-NEXT (BENCH-007): PASSED ✅ ===")
}
