package novelty

import (
	"testing"
	"time"

	"github.com/google/uuid"
	"github.com/vKS-Rajput/doge/internal/property"
)

func TestMDLAnomalyDetectorNormalResponse(t *testing.T) {
	detector := NewMDLAnomalyDetector(0.65)
	catalog := property.NewCatalog()

	normalObs := &MDLObservation{
		ID:         uuid.New(),
		URL:        "http://127.0.0.1:8080/api/v1/users",
		Method:     "GET",
		StatusCode: 200,
		Headers: map[string]string{
			"Content-Type": "application/json",
			"Date":         "Wed, 21 Oct 2026 07:28:00 GMT",
		},
		Body:        `{"status": "ok", "users": []}`,
		BodyLength:  30,
		PrincipalID: "user_1",
		Timestamp:   time.Now().UTC(),
	}

	res := detector.EvaluateObservation(normalObs, catalog)
	if res == nil {
		t.Fatalf("expected non-nil result")
	}

	if res.IsStructuralAnomaly {
		t.Errorf("expected normal response not to be flagged as structural anomaly, got score %.2f", res.AnomalyScore)
	}

	provisional := RepresentationExpansionOperator(res, normalObs)
	if provisional != nil {
		t.Errorf("expected nil provisional concept for non-anomalous observation")
	}
}

func TestMDLAnomalyDetectorStructuralDiscrepancy(t *testing.T) {
	detector := NewMDLAnomalyDetector(0.65)
	catalog := property.NewCatalog()

	anomalousObs := &MDLObservation{
		ID:         uuid.New(),
		URL:        "http://127.0.0.1:8080/api/v1/admin/debug_override",
		Method:     "POST",
		StatusCode: 200,
		Headers: map[string]string{
			"X-Internal-Backend-Trace": "cluster-east-internal-01",
			"X-Proxy-Debug-Route":      "direct://raw_bypass",
			"X-Cluster-Identity":       "root_canary_override",
		},
		Body:        `{"privileged_token": "supersecret_root_token_999", "internal_role": "admin", "debug": true}`,
		BodyLength:  95,
		PrincipalID: "guest",
		Timestamp:   time.Now().UTC(),
	}

	res := detector.EvaluateObservation(anomalousObs, catalog)
	if res == nil {
		t.Fatalf("expected non-nil result")
	}

	if !res.IsStructuralAnomaly {
		t.Errorf("expected anomalous response to be flagged as structural anomaly, got score %.2f", res.AnomalyScore)
	}

	if res.AnomalyScore < 0.65 {
		t.Errorf("expected anomaly score >= 0.65, got %.2f", res.AnomalyScore)
	}

	provisional := RepresentationExpansionOperator(res, anomalousObs)
	if provisional == nil {
		t.Fatalf("expected provisional concept generated by rho operator")
	}

	if provisional.DiscrepancyDim == "" {
		t.Errorf("expected non-empty discrepancy dimension")
	}

	t.Logf("Minted Provisional Concept from MDL anomaly: %s (dim=%s, score=%.2f)",
		provisional.ID, provisional.DiscrepancyDim, provisional.AnomalyScore)
}
