package main

import (
	"fmt"

	"github.com/spf13/cobra"
	"github.com/vKS-Rajput/doge/internal/app"
)

// newTasksCmd creates the 'tasks' command.
func newTasksCmd() *cobra.Command {
	var wsPath string
	var limit int
	var status string

	cmd := &cobra.Command{
		Use:   "tasks",
		Short: "Show research tasks",
		Long: `Show actionable research tasks generated by the Task Engine.

Tasks are prioritized by severity and linked to the insights
that generated them.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			if wsPath == "" {
				wsPath = "."
			}

			application, err := app.Open(cmd.Context(), wsPath)
			if err != nil {
				return fmt.Errorf("failed to open workspace: %w", err)
			}
			defer application.Shutdown()

			tasks, err := application.Tasks(cmd.Context(), status, limit)
			if err != nil {
				return fmt.Errorf("failed to query tasks: %w", err)
			}

			if len(tasks) == 0 {
				fmt.Println("No tasks yet.")
				return nil
			}

			fmt.Printf("Tasks (%d)\n", len(tasks))
			fmt.Println("─────────────────────────────────────────────")

			for _, t := range tasks {
				icon := priorityIcon(string(t.Priority))
				fmt.Printf("  %s [%s] %s\n", icon, t.Priority, t.Title)
				if t.Description != "" {
					// Show first line of description.
					desc := t.Description
					if idx := indexOf(desc, "\n"); idx > 0 {
						desc = desc[:idx]
					}
					fmt.Printf("       %s\n", desc)
				}
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&wsPath, "path", "", "workspace directory")
	cmd.Flags().IntVar(&limit, "limit", 25, "maximum number of tasks")
	cmd.Flags().StringVar(&status, "status", "", "filter by status (pending, in_progress, done, skipped)")
	return cmd
}

func priorityIcon(p string) string {
	switch p {
	case "critical":
		return "🔴"
	case "high":
		return "🟠"
	case "medium":
		return "🟡"
	case "low":
		return "🔵"
	default:
		return "⚪"
	}
}

func indexOf(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
